// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace protocol {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class FileDownloadMsg {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    internal static pbd::MessageDescriptor internal__static_protocol_FileDownloadReq__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::protocol.FileDownloadReq, global::protocol.FileDownloadReq.Builder> internal__static_protocol_FileDownloadReq__FieldAccessorTable;
    internal static pbd::MessageDescriptor internal__static_protocol_FileDownloadRsp__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::protocol.FileDownloadRsp, global::protocol.FileDownloadRsp.Builder> internal__static_protocol_FileDownloadRsp__FieldAccessorTable;
    internal static pbd::MessageDescriptor internal__static_protocol_FileDownloadOverRsp__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::protocol.FileDownloadOverRsp, global::protocol.FileDownloadOverRsp.Builder> internal__static_protocol_FileDownloadOverRsp__FieldAccessorTable;
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static FileDownloadMsg() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVGaWxlRG93bmxvYWRNc2cucHJvdG8SCHByb3RvY29sGhFJZGVudGl0eU1z", 
            "Zy5wcm90bxoRUHJvdG9EZWZpbmUucHJvdG8ijAEKD0ZpbGVEb3dubG9hZFJl", 
            "cRIqCgRJZGVuGAEgAigLMhwucHJvdG9jb2wuSWRlbnRpdHlJbmZvQ2xpTXNn", 
            "EicKA0NtZBgCIAEoDjIULnByb3RvY29sLkFjdGlvblR5cGU6BFNUT1ASEgoI", 
            "RmlsZU5hbWUYAyABKAk6ABIQCgVCZWdpbhgEIAEoDToBMCKUAQoPRmlsZURv", 
            "d25sb2FkUnNwEioKBElkZW4YASACKAsyHC5wcm90b2NvbC5JZGVudGl0eUlu", 
            "Zm9DbGlNc2cSDAoEQ29kZRgCIAIoDRIVCgpSZW1haW5TaXplGAMgASgNOgEw", 
            "EhAKBUJlZ2luGAQgASgNOgEwEg4KA0VuZBgFIAEoDToBMBIOCgREYXRhGAYg", 
            "ASgMOgAieAoTRmlsZURvd25sb2FkT3ZlclJzcBIqCgRJZGVuGAEgAigLMhwu", 
            "cHJvdG9jb2wuSWRlbnRpdHlJbmZvQ2xpTXNnEhAKCEZpbGVOYW1lGAIgASgJ", 
          "Eg8KBFNpemUYAyABKA06ATASEgoIQ2hlY2tTdW0YBCABKAk6AA=="));
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        internal__static_protocol_FileDownloadReq__Descriptor = Descriptor.MessageTypes[0];
        internal__static_protocol_FileDownloadReq__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::protocol.FileDownloadReq, global::protocol.FileDownloadReq.Builder>(internal__static_protocol_FileDownloadReq__Descriptor,
                new string[] { "Iden", "Cmd", "FileName", "Begin", });
        internal__static_protocol_FileDownloadRsp__Descriptor = Descriptor.MessageTypes[1];
        internal__static_protocol_FileDownloadRsp__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::protocol.FileDownloadRsp, global::protocol.FileDownloadRsp.Builder>(internal__static_protocol_FileDownloadRsp__Descriptor,
                new string[] { "Iden", "Code", "RemainSize", "Begin", "End", "Data", });
        internal__static_protocol_FileDownloadOverRsp__Descriptor = Descriptor.MessageTypes[2];
        internal__static_protocol_FileDownloadOverRsp__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::protocol.FileDownloadOverRsp, global::protocol.FileDownloadOverRsp.Builder>(internal__static_protocol_FileDownloadOverRsp__Descriptor,
                new string[] { "Iden", "FileName", "Size", "CheckSum", });
        return null;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          global::protocol.IdentityMsg.Descriptor, 
          global::protocol.ProtoDefine.Descriptor, 
          }, assigner);
    }
    #endregion
    
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class FileDownloadReq : pb::GeneratedMessage<FileDownloadReq, FileDownloadReq.Builder> {
    private FileDownloadReq() { }
    private static readonly FileDownloadReq defaultInstance = new FileDownloadReq().MakeReadOnly();
    private static readonly string[] _fileDownloadReqFieldNames = new string[] { "Begin", "Cmd", "FileName", "Iden" };
    private static readonly uint[] _fileDownloadReqFieldTags = new uint[] { 32, 16, 26, 10 };
    public static FileDownloadReq DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override FileDownloadReq DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override FileDownloadReq ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::protocol.FileDownloadMsg.internal__static_protocol_FileDownloadReq__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<FileDownloadReq, FileDownloadReq.Builder> InternalFieldAccessors {
      get { return global::protocol.FileDownloadMsg.internal__static_protocol_FileDownloadReq__FieldAccessorTable; }
    }
    
    public const int IdenFieldNumber = 1;
    private bool hasIden;
    private global::protocol.IdentityInfoCliMsg iden_;
    public bool HasIden {
      get { return hasIden; }
    }
    public global::protocol.IdentityInfoCliMsg Iden {
      get { return iden_ ?? global::protocol.IdentityInfoCliMsg.DefaultInstance; }
    }
    
    public const int CmdFieldNumber = 2;
    private bool hasCmd;
    private global::protocol.ActionType cmd_ = global::protocol.ActionType.STOP;
    public bool HasCmd {
      get { return hasCmd; }
    }
    public global::protocol.ActionType Cmd {
      get { return cmd_; }
    }
    
    public const int FileNameFieldNumber = 3;
    private bool hasFileName;
    private string fileName_ = "";
    public bool HasFileName {
      get { return hasFileName; }
    }
    public string FileName {
      get { return fileName_; }
    }
    
    public const int BeginFieldNumber = 4;
    private bool hasBegin;
    private uint begin_;
    public bool HasBegin {
      get { return hasBegin; }
    }
    [global::System.CLSCompliant(false)]
    public uint Begin {
      get { return begin_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasIden) return false;
        if (!Iden.IsInitialized) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      CalcSerializedSize();
      string[] field_names = _fileDownloadReqFieldNames;
      if (hasIden) {
        output.WriteMessage(1, field_names[3], Iden);
      }
      if (hasCmd) {
        output.WriteEnum(2, field_names[1], (int) Cmd, Cmd);
      }
      if (hasFileName) {
        output.WriteString(3, field_names[2], FileName);
      }
      if (hasBegin) {
        output.WriteUInt32(4, field_names[0], Begin);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        return CalcSerializedSize();
      }
    }
    
    private int CalcSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (hasIden) {
        size += pb::CodedOutputStream.ComputeMessageSize(1, Iden);
      }
      if (hasCmd) {
        size += pb::CodedOutputStream.ComputeEnumSize(2, (int) Cmd);
      }
      if (hasFileName) {
        size += pb::CodedOutputStream.ComputeStringSize(3, FileName);
      }
      if (hasBegin) {
        size += pb::CodedOutputStream.ComputeUInt32Size(4, Begin);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
    public static FileDownloadReq ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static FileDownloadReq ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static FileDownloadReq ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static FileDownloadReq ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static FileDownloadReq ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static FileDownloadReq ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static FileDownloadReq ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static FileDownloadReq ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static FileDownloadReq ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static FileDownloadReq ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private FileDownloadReq MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(FileDownloadReq prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<FileDownloadReq, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(FileDownloadReq cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private FileDownloadReq result;
      
      private FileDownloadReq PrepareBuilder() {
        if (resultIsReadOnly) {
          FileDownloadReq original = result;
          result = new FileDownloadReq();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override FileDownloadReq MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::protocol.FileDownloadReq.Descriptor; }
      }
      
      public override FileDownloadReq DefaultInstanceForType {
        get { return global::protocol.FileDownloadReq.DefaultInstance; }
      }
      
      public override FileDownloadReq BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is FileDownloadReq) {
          return MergeFrom((FileDownloadReq) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(FileDownloadReq other) {
        if (other == global::protocol.FileDownloadReq.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasIden) {
          MergeIden(other.Iden);
        }
        if (other.HasCmd) {
          Cmd = other.Cmd;
        }
        if (other.HasFileName) {
          FileName = other.FileName;
        }
        if (other.HasBegin) {
          Begin = other.Begin;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_fileDownloadReqFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _fileDownloadReqFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              global::protocol.IdentityInfoCliMsg.Builder subBuilder = global::protocol.IdentityInfoCliMsg.CreateBuilder();
              if (result.hasIden) {
                subBuilder.MergeFrom(Iden);
              }
              input.ReadMessage(subBuilder, extensionRegistry);
              Iden = subBuilder.BuildPartial();
              break;
            }
            case 16: {
              object unknown;
              if(input.ReadEnum(ref result.cmd_, out unknown)) {
                result.hasCmd = true;
              } else if(unknown is int) {
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                unknownFields.MergeVarintField(2, (ulong)(int)unknown);
              }
              break;
            }
            case 26: {
              result.hasFileName = input.ReadString(ref result.fileName_);
              break;
            }
            case 32: {
              result.hasBegin = input.ReadUInt32(ref result.begin_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasIden {
       get { return result.hasIden; }
      }
      public global::protocol.IdentityInfoCliMsg Iden {
        get { return result.Iden; }
        set { SetIden(value); }
      }
      public Builder SetIden(global::protocol.IdentityInfoCliMsg value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasIden = true;
        result.iden_ = value;
        return this;
      }
      public Builder SetIden(global::protocol.IdentityInfoCliMsg.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.hasIden = true;
        result.iden_ = builderForValue.Build();
        return this;
      }
      public Builder MergeIden(global::protocol.IdentityInfoCliMsg value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        if (result.hasIden &&
            result.iden_ != global::protocol.IdentityInfoCliMsg.DefaultInstance) {
            result.iden_ = global::protocol.IdentityInfoCliMsg.CreateBuilder(result.iden_).MergeFrom(value).BuildPartial();
        } else {
          result.iden_ = value;
        }
        result.hasIden = true;
        return this;
      }
      public Builder ClearIden() {
        PrepareBuilder();
        result.hasIden = false;
        result.iden_ = null;
        return this;
      }
      
      public bool HasCmd {
       get { return result.hasCmd; }
      }
      public global::protocol.ActionType Cmd {
        get { return result.Cmd; }
        set { SetCmd(value); }
      }
      public Builder SetCmd(global::protocol.ActionType value) {
        PrepareBuilder();
        result.hasCmd = true;
        result.cmd_ = value;
        return this;
      }
      public Builder ClearCmd() {
        PrepareBuilder();
        result.hasCmd = false;
        result.cmd_ = global::protocol.ActionType.STOP;
        return this;
      }
      
      public bool HasFileName {
        get { return result.hasFileName; }
      }
      public string FileName {
        get { return result.FileName; }
        set { SetFileName(value); }
      }
      public Builder SetFileName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasFileName = true;
        result.fileName_ = value;
        return this;
      }
      public Builder ClearFileName() {
        PrepareBuilder();
        result.hasFileName = false;
        result.fileName_ = "";
        return this;
      }
      
      public bool HasBegin {
        get { return result.hasBegin; }
      }
      [global::System.CLSCompliant(false)]
      public uint Begin {
        get { return result.Begin; }
        set { SetBegin(value); }
      }
      [global::System.CLSCompliant(false)]
      public Builder SetBegin(uint value) {
        PrepareBuilder();
        result.hasBegin = true;
        result.begin_ = value;
        return this;
      }
      public Builder ClearBegin() {
        PrepareBuilder();
        result.hasBegin = false;
        result.begin_ = 0;
        return this;
      }
    }
    static FileDownloadReq() {
      object.ReferenceEquals(global::protocol.FileDownloadMsg.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class FileDownloadRsp : pb::GeneratedMessage<FileDownloadRsp, FileDownloadRsp.Builder> {
    private FileDownloadRsp() { }
    private static readonly FileDownloadRsp defaultInstance = new FileDownloadRsp().MakeReadOnly();
    private static readonly string[] _fileDownloadRspFieldNames = new string[] { "Begin", "Code", "Data", "End", "Iden", "RemainSize" };
    private static readonly uint[] _fileDownloadRspFieldTags = new uint[] { 32, 16, 50, 40, 10, 24 };
    public static FileDownloadRsp DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override FileDownloadRsp DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override FileDownloadRsp ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::protocol.FileDownloadMsg.internal__static_protocol_FileDownloadRsp__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<FileDownloadRsp, FileDownloadRsp.Builder> InternalFieldAccessors {
      get { return global::protocol.FileDownloadMsg.internal__static_protocol_FileDownloadRsp__FieldAccessorTable; }
    }
    
    public const int IdenFieldNumber = 1;
    private bool hasIden;
    private global::protocol.IdentityInfoCliMsg iden_;
    public bool HasIden {
      get { return hasIden; }
    }
    public global::protocol.IdentityInfoCliMsg Iden {
      get { return iden_ ?? global::protocol.IdentityInfoCliMsg.DefaultInstance; }
    }
    
    public const int CodeFieldNumber = 2;
    private bool hasCode;
    private uint code_;
    public bool HasCode {
      get { return hasCode; }
    }
    [global::System.CLSCompliant(false)]
    public uint Code {
      get { return code_; }
    }
    
    public const int RemainSizeFieldNumber = 3;
    private bool hasRemainSize;
    private uint remainSize_;
    public bool HasRemainSize {
      get { return hasRemainSize; }
    }
    [global::System.CLSCompliant(false)]
    public uint RemainSize {
      get { return remainSize_; }
    }
    
    public const int BeginFieldNumber = 4;
    private bool hasBegin;
    private uint begin_;
    public bool HasBegin {
      get { return hasBegin; }
    }
    [global::System.CLSCompliant(false)]
    public uint Begin {
      get { return begin_; }
    }
    
    public const int EndFieldNumber = 5;
    private bool hasEnd;
    private uint end_;
    public bool HasEnd {
      get { return hasEnd; }
    }
    [global::System.CLSCompliant(false)]
    public uint End {
      get { return end_; }
    }
    
    public const int DataFieldNumber = 6;
    private bool hasData;
    private pb::ByteString data_ = (pb::ByteString) global::protocol.FileDownloadRsp.Descriptor.Fields[5].DefaultValue;
    public bool HasData {
      get { return hasData; }
    }
    public pb::ByteString Data {
      get { return data_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasIden) return false;
        if (!hasCode) return false;
        if (!Iden.IsInitialized) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      CalcSerializedSize();
      string[] field_names = _fileDownloadRspFieldNames;
      if (hasIden) {
        output.WriteMessage(1, field_names[4], Iden);
      }
      if (hasCode) {
        output.WriteUInt32(2, field_names[1], Code);
      }
      if (hasRemainSize) {
        output.WriteUInt32(3, field_names[5], RemainSize);
      }
      if (hasBegin) {
        output.WriteUInt32(4, field_names[0], Begin);
      }
      if (hasEnd) {
        output.WriteUInt32(5, field_names[3], End);
      }
      if (hasData) {
        output.WriteBytes(6, field_names[2], Data);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        return CalcSerializedSize();
      }
    }
    
    private int CalcSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (hasIden) {
        size += pb::CodedOutputStream.ComputeMessageSize(1, Iden);
      }
      if (hasCode) {
        size += pb::CodedOutputStream.ComputeUInt32Size(2, Code);
      }
      if (hasRemainSize) {
        size += pb::CodedOutputStream.ComputeUInt32Size(3, RemainSize);
      }
      if (hasBegin) {
        size += pb::CodedOutputStream.ComputeUInt32Size(4, Begin);
      }
      if (hasEnd) {
        size += pb::CodedOutputStream.ComputeUInt32Size(5, End);
      }
      if (hasData) {
        size += pb::CodedOutputStream.ComputeBytesSize(6, Data);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
    public static FileDownloadRsp ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static FileDownloadRsp ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static FileDownloadRsp ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static FileDownloadRsp ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static FileDownloadRsp ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static FileDownloadRsp ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static FileDownloadRsp ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static FileDownloadRsp ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static FileDownloadRsp ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static FileDownloadRsp ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private FileDownloadRsp MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(FileDownloadRsp prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<FileDownloadRsp, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(FileDownloadRsp cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private FileDownloadRsp result;
      
      private FileDownloadRsp PrepareBuilder() {
        if (resultIsReadOnly) {
          FileDownloadRsp original = result;
          result = new FileDownloadRsp();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override FileDownloadRsp MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::protocol.FileDownloadRsp.Descriptor; }
      }
      
      public override FileDownloadRsp DefaultInstanceForType {
        get { return global::protocol.FileDownloadRsp.DefaultInstance; }
      }
      
      public override FileDownloadRsp BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is FileDownloadRsp) {
          return MergeFrom((FileDownloadRsp) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(FileDownloadRsp other) {
        if (other == global::protocol.FileDownloadRsp.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasIden) {
          MergeIden(other.Iden);
        }
        if (other.HasCode) {
          Code = other.Code;
        }
        if (other.HasRemainSize) {
          RemainSize = other.RemainSize;
        }
        if (other.HasBegin) {
          Begin = other.Begin;
        }
        if (other.HasEnd) {
          End = other.End;
        }
        if (other.HasData) {
          Data = other.Data;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_fileDownloadRspFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _fileDownloadRspFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              global::protocol.IdentityInfoCliMsg.Builder subBuilder = global::protocol.IdentityInfoCliMsg.CreateBuilder();
              if (result.hasIden) {
                subBuilder.MergeFrom(Iden);
              }
              input.ReadMessage(subBuilder, extensionRegistry);
              Iden = subBuilder.BuildPartial();
              break;
            }
            case 16: {
              result.hasCode = input.ReadUInt32(ref result.code_);
              break;
            }
            case 24: {
              result.hasRemainSize = input.ReadUInt32(ref result.remainSize_);
              break;
            }
            case 32: {
              result.hasBegin = input.ReadUInt32(ref result.begin_);
              break;
            }
            case 40: {
              result.hasEnd = input.ReadUInt32(ref result.end_);
              break;
            }
            case 50: {
              result.hasData = input.ReadBytes(ref result.data_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasIden {
       get { return result.hasIden; }
      }
      public global::protocol.IdentityInfoCliMsg Iden {
        get { return result.Iden; }
        set { SetIden(value); }
      }
      public Builder SetIden(global::protocol.IdentityInfoCliMsg value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasIden = true;
        result.iden_ = value;
        return this;
      }
      public Builder SetIden(global::protocol.IdentityInfoCliMsg.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.hasIden = true;
        result.iden_ = builderForValue.Build();
        return this;
      }
      public Builder MergeIden(global::protocol.IdentityInfoCliMsg value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        if (result.hasIden &&
            result.iden_ != global::protocol.IdentityInfoCliMsg.DefaultInstance) {
            result.iden_ = global::protocol.IdentityInfoCliMsg.CreateBuilder(result.iden_).MergeFrom(value).BuildPartial();
        } else {
          result.iden_ = value;
        }
        result.hasIden = true;
        return this;
      }
      public Builder ClearIden() {
        PrepareBuilder();
        result.hasIden = false;
        result.iden_ = null;
        return this;
      }
      
      public bool HasCode {
        get { return result.hasCode; }
      }
      [global::System.CLSCompliant(false)]
      public uint Code {
        get { return result.Code; }
        set { SetCode(value); }
      }
      [global::System.CLSCompliant(false)]
      public Builder SetCode(uint value) {
        PrepareBuilder();
        result.hasCode = true;
        result.code_ = value;
        return this;
      }
      public Builder ClearCode() {
        PrepareBuilder();
        result.hasCode = false;
        result.code_ = 0;
        return this;
      }
      
      public bool HasRemainSize {
        get { return result.hasRemainSize; }
      }
      [global::System.CLSCompliant(false)]
      public uint RemainSize {
        get { return result.RemainSize; }
        set { SetRemainSize(value); }
      }
      [global::System.CLSCompliant(false)]
      public Builder SetRemainSize(uint value) {
        PrepareBuilder();
        result.hasRemainSize = true;
        result.remainSize_ = value;
        return this;
      }
      public Builder ClearRemainSize() {
        PrepareBuilder();
        result.hasRemainSize = false;
        result.remainSize_ = 0;
        return this;
      }
      
      public bool HasBegin {
        get { return result.hasBegin; }
      }
      [global::System.CLSCompliant(false)]
      public uint Begin {
        get { return result.Begin; }
        set { SetBegin(value); }
      }
      [global::System.CLSCompliant(false)]
      public Builder SetBegin(uint value) {
        PrepareBuilder();
        result.hasBegin = true;
        result.begin_ = value;
        return this;
      }
      public Builder ClearBegin() {
        PrepareBuilder();
        result.hasBegin = false;
        result.begin_ = 0;
        return this;
      }
      
      public bool HasEnd {
        get { return result.hasEnd; }
      }
      [global::System.CLSCompliant(false)]
      public uint End {
        get { return result.End; }
        set { SetEnd(value); }
      }
      [global::System.CLSCompliant(false)]
      public Builder SetEnd(uint value) {
        PrepareBuilder();
        result.hasEnd = true;
        result.end_ = value;
        return this;
      }
      public Builder ClearEnd() {
        PrepareBuilder();
        result.hasEnd = false;
        result.end_ = 0;
        return this;
      }
      
      public bool HasData {
        get { return result.hasData; }
      }
      public pb::ByteString Data {
        get { return result.Data; }
        set { SetData(value); }
      }
      public Builder SetData(pb::ByteString value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasData = true;
        result.data_ = value;
        return this;
      }
      public Builder ClearData() {
        PrepareBuilder();
        result.hasData = false;
        result.data_ = (pb::ByteString) global::protocol.FileDownloadRsp.Descriptor.Fields[5].DefaultValue;
        return this;
      }
    }
    static FileDownloadRsp() {
      object.ReferenceEquals(global::protocol.FileDownloadMsg.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class FileDownloadOverRsp : pb::GeneratedMessage<FileDownloadOverRsp, FileDownloadOverRsp.Builder> {
    private FileDownloadOverRsp() { }
    private static readonly FileDownloadOverRsp defaultInstance = new FileDownloadOverRsp().MakeReadOnly();
    private static readonly string[] _fileDownloadOverRspFieldNames = new string[] { "CheckSum", "FileName", "Iden", "Size" };
    private static readonly uint[] _fileDownloadOverRspFieldTags = new uint[] { 34, 18, 10, 24 };
    public static FileDownloadOverRsp DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override FileDownloadOverRsp DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override FileDownloadOverRsp ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::protocol.FileDownloadMsg.internal__static_protocol_FileDownloadOverRsp__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<FileDownloadOverRsp, FileDownloadOverRsp.Builder> InternalFieldAccessors {
      get { return global::protocol.FileDownloadMsg.internal__static_protocol_FileDownloadOverRsp__FieldAccessorTable; }
    }
    
    public const int IdenFieldNumber = 1;
    private bool hasIden;
    private global::protocol.IdentityInfoCliMsg iden_;
    public bool HasIden {
      get { return hasIden; }
    }
    public global::protocol.IdentityInfoCliMsg Iden {
      get { return iden_ ?? global::protocol.IdentityInfoCliMsg.DefaultInstance; }
    }
    
    public const int FileNameFieldNumber = 2;
    private bool hasFileName;
    private string fileName_ = "";
    public bool HasFileName {
      get { return hasFileName; }
    }
    public string FileName {
      get { return fileName_; }
    }
    
    public const int SizeFieldNumber = 3;
    private bool hasSize;
    private uint size_;
    public bool HasSize {
      get { return hasSize; }
    }
    [global::System.CLSCompliant(false)]
    public uint Size {
      get { return size_; }
    }
    
    public const int CheckSumFieldNumber = 4;
    private bool hasCheckSum;
    private string checkSum_ = "";
    public bool HasCheckSum {
      get { return hasCheckSum; }
    }
    public string CheckSum {
      get { return checkSum_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasIden) return false;
        if (!Iden.IsInitialized) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      CalcSerializedSize();
      string[] field_names = _fileDownloadOverRspFieldNames;
      if (hasIden) {
        output.WriteMessage(1, field_names[2], Iden);
      }
      if (hasFileName) {
        output.WriteString(2, field_names[1], FileName);
      }
      if (hasSize) {
        output.WriteUInt32(3, field_names[3], Size);
      }
      if (hasCheckSum) {
        output.WriteString(4, field_names[0], CheckSum);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        return CalcSerializedSize();
      }
    }
    
    private int CalcSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (hasIden) {
        size += pb::CodedOutputStream.ComputeMessageSize(1, Iden);
      }
      if (hasFileName) {
        size += pb::CodedOutputStream.ComputeStringSize(2, FileName);
      }
      if (hasSize) {
        size += pb::CodedOutputStream.ComputeUInt32Size(3, Size);
      }
      if (hasCheckSum) {
        size += pb::CodedOutputStream.ComputeStringSize(4, CheckSum);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
    public static FileDownloadOverRsp ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static FileDownloadOverRsp ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static FileDownloadOverRsp ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static FileDownloadOverRsp ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static FileDownloadOverRsp ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static FileDownloadOverRsp ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static FileDownloadOverRsp ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static FileDownloadOverRsp ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static FileDownloadOverRsp ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static FileDownloadOverRsp ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private FileDownloadOverRsp MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(FileDownloadOverRsp prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<FileDownloadOverRsp, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(FileDownloadOverRsp cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private FileDownloadOverRsp result;
      
      private FileDownloadOverRsp PrepareBuilder() {
        if (resultIsReadOnly) {
          FileDownloadOverRsp original = result;
          result = new FileDownloadOverRsp();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override FileDownloadOverRsp MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::protocol.FileDownloadOverRsp.Descriptor; }
      }
      
      public override FileDownloadOverRsp DefaultInstanceForType {
        get { return global::protocol.FileDownloadOverRsp.DefaultInstance; }
      }
      
      public override FileDownloadOverRsp BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is FileDownloadOverRsp) {
          return MergeFrom((FileDownloadOverRsp) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(FileDownloadOverRsp other) {
        if (other == global::protocol.FileDownloadOverRsp.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasIden) {
          MergeIden(other.Iden);
        }
        if (other.HasFileName) {
          FileName = other.FileName;
        }
        if (other.HasSize) {
          Size = other.Size;
        }
        if (other.HasCheckSum) {
          CheckSum = other.CheckSum;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_fileDownloadOverRspFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _fileDownloadOverRspFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              global::protocol.IdentityInfoCliMsg.Builder subBuilder = global::protocol.IdentityInfoCliMsg.CreateBuilder();
              if (result.hasIden) {
                subBuilder.MergeFrom(Iden);
              }
              input.ReadMessage(subBuilder, extensionRegistry);
              Iden = subBuilder.BuildPartial();
              break;
            }
            case 18: {
              result.hasFileName = input.ReadString(ref result.fileName_);
              break;
            }
            case 24: {
              result.hasSize = input.ReadUInt32(ref result.size_);
              break;
            }
            case 34: {
              result.hasCheckSum = input.ReadString(ref result.checkSum_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasIden {
       get { return result.hasIden; }
      }
      public global::protocol.IdentityInfoCliMsg Iden {
        get { return result.Iden; }
        set { SetIden(value); }
      }
      public Builder SetIden(global::protocol.IdentityInfoCliMsg value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasIden = true;
        result.iden_ = value;
        return this;
      }
      public Builder SetIden(global::protocol.IdentityInfoCliMsg.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.hasIden = true;
        result.iden_ = builderForValue.Build();
        return this;
      }
      public Builder MergeIden(global::protocol.IdentityInfoCliMsg value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        if (result.hasIden &&
            result.iden_ != global::protocol.IdentityInfoCliMsg.DefaultInstance) {
            result.iden_ = global::protocol.IdentityInfoCliMsg.CreateBuilder(result.iden_).MergeFrom(value).BuildPartial();
        } else {
          result.iden_ = value;
        }
        result.hasIden = true;
        return this;
      }
      public Builder ClearIden() {
        PrepareBuilder();
        result.hasIden = false;
        result.iden_ = null;
        return this;
      }
      
      public bool HasFileName {
        get { return result.hasFileName; }
      }
      public string FileName {
        get { return result.FileName; }
        set { SetFileName(value); }
      }
      public Builder SetFileName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasFileName = true;
        result.fileName_ = value;
        return this;
      }
      public Builder ClearFileName() {
        PrepareBuilder();
        result.hasFileName = false;
        result.fileName_ = "";
        return this;
      }
      
      public bool HasSize {
        get { return result.hasSize; }
      }
      [global::System.CLSCompliant(false)]
      public uint Size {
        get { return result.Size; }
        set { SetSize(value); }
      }
      [global::System.CLSCompliant(false)]
      public Builder SetSize(uint value) {
        PrepareBuilder();
        result.hasSize = true;
        result.size_ = value;
        return this;
      }
      public Builder ClearSize() {
        PrepareBuilder();
        result.hasSize = false;
        result.size_ = 0;
        return this;
      }
      
      public bool HasCheckSum {
        get { return result.hasCheckSum; }
      }
      public string CheckSum {
        get { return result.CheckSum; }
        set { SetCheckSum(value); }
      }
      public Builder SetCheckSum(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasCheckSum = true;
        result.checkSum_ = value;
        return this;
      }
      public Builder ClearCheckSum() {
        PrepareBuilder();
        result.hasCheckSum = false;
        result.checkSum_ = "";
        return this;
      }
    }
    static FileDownloadOverRsp() {
      object.ReferenceEquals(global::protocol.FileDownloadMsg.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
