// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace protocol {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class ProtoDefine {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static ProtoDefine() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFQcm90b0RlZmluZS5wcm90bxIIcHJvdG9jb2wqVQoKUmVzdWx0Q29kZRIL", 
            "CgdTVUNDRVNTEAASCAoERkFJTBABEgsKB1BCX0ZBSUwQAhINCglBVVRIX0ZB", 
            "SUwQAxIUChBERVZJQ0VfVFlQRV9GQUlMEAQqJAoJT3B0U3RhdHVzEgsKB1JV", 
            "Tk5JTkcQABIKCgZGSU5OQUwQASokCgpEZXZpY2VUeXBlEgoKBkRfMzcxNhAA", 
            "EgoKBkRfSzNWMhABKiEKCkFjdGlvblR5cGUSCAoEU1RPUBAAEgkKBVNUQVJU", 
          "EAEqJQoKRGV2aWNlU3RhdBILCgdPRkZMSU5FEAASCgoGT05MSU5FEAE="));
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        return null;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          }, assigner);
    }
    #endregion
    
  }
  #region Enums
  public enum ResultCode {
    SUCCESS = 0,
    FAIL = 1,
    PB_FAIL = 2,
    AUTH_FAIL = 3,
    DEVICE_TYPE_FAIL = 4,
  }
  
  public enum OptStatus {
    RUNNING = 0,
    FINNAL = 1,
  }
  
  public enum DeviceType {
    D_3716 = 0,
    D_K3V2 = 1,
  }
  
  public enum ActionType {
    STOP = 0,
    START = 1,
  }
  
  public enum DeviceStat {
    OFFLINE = 0,
    ONLINE = 1,
  }
  
  #endregion
  
}

#endregion Designer generated code
